### ISSUE TITLE
Regeneration effect not applying correctly.

### ISSUE THREAD

**Issue by MindBrain27** [Witixin1512/ArmorSetEffects#10]
The regeneration effect gives the visual effect of it working while wearing the set, but won't actually give regeneration until I remove a piece of the set for some reason. I have just been editing the example.

`val iron_set = new ArmorSetEffect("iron_set")
               .inSlot(<equipmentslottype:head>, <item:minecraft:iron_helmet>)
               .inSlot(<equipmentslottype:chest>, <item:minecraft:iron_chestplate>)
               .inSlot(<equipmentslottype:legs>, <item:minecraft:iron_leggings>)
               .inSlot(<equipmentslottype:feet>, <item:minecraft:iron_boots>)
               .setIgnoreNBT()
               .addEffect(<effect:minecraft:regeneration>.newInstance(50, 3))
               .addImmunity(<effect:minecraft:blindness>)
               .addAttackerEffect(<effect:minecraft:poison>.newInstance(60, 1));
iron_set.register();`

**Comment by MindBrain27** [comment]
I just read the other open issue's further comments and can work with the timer effect issue for now, thanks!

**Comment by Witixin1512** [comment]
Yep! Sorry about that, Regeneration, Hunger, Poison and Wither are modified according to their duration in vanilla.
