### ISSUE TITLE
Set Effects Are Applied Inconsistently 

### ISSUE THREAD

**Issue by RobertHDPotatoes** [Witixin1512/ArmorSetEffects#2]
Minecraft Version: 1.16.5
Forge Version:  36.2.9
CraftTweaker Version: 1.16.5-7.1.2.457
Armor Set Effects Version: 1.16.5-1.0.2

Problem:
Upon joining a world, the set effects script will load and will work properly. However, after a short amount of time the set effect will start becoming inconsistent, at times not refreshing the effects for upwards of 10 seconds,  and other times refreshing every second. Basically it seems like the internal timer for refreshing the set effect is inconsistent, but I'm not really sure what's going on.

Expected behavior: I am basically using the default script, but my specific script can be found here: (https://pastebin.com/03uLEnWM) and so I expect that while wearing a full set of iron armor, the regeneration effect and the angry villager particles will pop up at consistent intervals, specifically before the regeneration runs out. 

I haven't tried to replicate it on a completely clean version of Minecraft, but it should still happen in a clean install.

To replicate:
1: Install CraftTweaker
2: Install Armor Set Effects
3: Load up my script, or any similar script
4: Script gives effects at inconsistent intervals.

If you cannot replicate this issue, let me know and I can provide log files as necessary.

**Comment by Witixin1512** [comment]
I believe I fixed it, I uploaded a file to CF that should fix it. If it prevails let me know.
Also, you should be able to extend the time of the effect changing the ticks it is applied in the `newInstance` method, as well as the amplifier, the ArmorSetEffects currently tick once every 5 seconds.

**Comment by RobertHDPotatoes** [comment]
Seems to work perfectly fine now, thanks for the fast fix! Also, if this isn't already possible with CraftTweaker, would it be possible to add a feature to allow ArmorSetEffects to be ticked more often, for example every second? I think it'd be nice to be able to control that, specifically for the added particle effects. If it is possible already, could I get an example/link to the documentation to try to figure it out?

**Comment by Witixin1512** [comment]
You'd have to reimplement most of the logic I think.
I'm gonna look into that, I might add another parameter. Would something like this work?
`addParticle(name, offsets, amountOfParticles, cycles) `

**Comment by RobertHDPotatoes** [comment]
Ah, that'd be a good solution! Also, forgive me but I've found another bug haha. This one's pretty minor, but I'm gonna make a proper bug report because it's oddly specific, and pretty peculiar honestly
