### ISSUE TITLE
The Command "/reload" is not fully respected

### ISSUE THREAD

**Issue by RobertHDPotatoes** [Witixin1512/ArmorSetEffects#3]
Minecraft Version: 1.16.5
Forge Version: 36.2.9
CraftTweaker Version: 1.16.5-7.1.2.457
Armor Set Effects Version: 1.16.5-1.0.3

Problem: When changing a script, if you increase the duration of any .addEffect and then do /reload, it WILL be respected and it will update and reflect your changes in game. However, when you decrease the duration of any .addEffect and do /reload, it WILL NOT respect your changes, and will still be whatever higher value it was before the /reload. If you completely restart the game, it WILL respect your duration decrease. This seems to be only for decreasing the duration, and only when trying to use /reload.

Expected behavior: If I decrease the duration of my .addEffect and do /reload, I expect the duration to decrease. 

This may also happen on .addAttackerEffect, I'm not sure. If this isn't replicable, I can share my logs if necessary.

**Comment by Witixin1512** [comment]
Thank you for finding out these bugs! 
Should be fixed in the newest build.

**Comment by RobertHDPotatoes** [comment]
Thanks, can confirm this is fixed!

**Comment by Witixin1512** [comment]
Let me know if there's something else, i'll look into the particle cycles this weekend
