### ISSUE TITLE
.addAttackEffect does not work for anything except melee

### ISSUE THREAD

**Issue by RobertHDPotatoes** [Witixin1512/ArmorSetEffects#9]
If you use .addAttackEffect on a script with the item being a Crossbow, Bow, or a Trident, then it does not give the effect with their ranged attacks. Throwing a trident does not give the added attack effect (Although using it in melee will), and shooting arrows with both bow types does not give the attack effect. Similarly, if you have any mods installed that have weapons that have a ranged attack (Ice And Fire's Phantasmal Sword, which shoots ghost swords as well as functioning as a sword comes to mind) their ranged attacks do not work with .addAttackEffect either.

This may be an awkward problem to try to solve, because it's a little funky how punching someone with a bow gives them .addAttackEffect's but shooting an arrow doesn't. Possibly another Instance Method, like .addRangedAttackEffect that makes melee not give the effect, but ranged attacks do? Lol, I'm not really sure, and if this is too much of a pain in the butt to try to figure out or implement there's no need to add this because I feel like it's a pretty specific use case haha. If you do come up with a solution that can be implemented without doing a ton of work, that would be great though!

**Comment by Witixin1512** [comment]
I'm fairly sure I know what causes this.
In case you ever do anything using DamageSources with CrT, the DamageSource that damages an entity is an arrow, which is fired by an entity.
I only check if the direct damage source is a Living Entity though, going to push a fix between today and tomorrow, I'll put that on the docs page with the previous things and the JEITweaker docs.

BTW, you shouldn't be concerned asking about things that are a ton of work, I still need to fix attributes, so if you have any more features, let me know.

**Comment by RobertHDPotatoes** [comment]
Alright! I also recently realized something, status effects such as wither, poison, and regeneration no longer work correctly if they are added using .addEffect. Seems to be only effects that are time sensitive? If you do:
".addEffect(<effect:minecraft:regeneration>.newInstance(100, 1).hideParticles())"
You regenerate MUCH faster than you should. Similarly, if you do 
.addEffect(<effect:minecraft:regeneration>.newInstance(5, 1).hideParticles())
You don't regenerate at all.

**Comment by Witixin1512** [comment]
I'll look into it. 
I'm not manipulating the effects, just converting from CT effect to internal Effect and applying them

**Comment by Witixin1512** [comment]
These effects are hardcoded to act differently based on their duration, it's how the game works.
There's nothing I can do directly lol
